# Setup
title: Kalpaj Chaudhari
tagline: Aspiring software professional
url: https://daedroza.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Kalpaj Chaudhari
  url: https://daedroza.github.io
  email: kalpaj1997@gmail.com

# Custom vars
version: 3.0.0
